config/routes.rb
Rails4::Application.routes.draw do
  resources :comments

  scope ':locale' do
    devise_for :users

    resources :presentations do
      resources :comments
      collection do
        get :tags
      end
    end

    match 'presentations/:id/subscribe' => 'presentations#subscribe', :as => 'subscribe'
    match 'presentations/:id/subscribe_create' => 'presentations#subscribe_create', :as => 'subscribe_create'
    match 'presentations/:id/subscribe_destroy' => 'presentations#subscribe_destroy', :as => 'subscribe_destroy'
    match 'presentations/:id/run' => 'presentations#run', :as => 'run_presentation'
    match 'presentations/:id/watch' => 'presentations#watch', :as => 'watch_presentation'
    match 'index_public' => 'presentations#index_public', :as => 'index_public_presentations'
    match 'index_private' => 'presentations#index_private', :as => 'index_private_presentations'

    match 'welcome' => 'welcome#welcome'
    match 'profile' => 'welcome#profile'
    match 'aboutus' => 'welcome#aboutus'
  end
  match 'backend/colorize' => 'backend#colorize'

  match '/(:locale)' => 'welcome#welcome', :as => :root

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  cattr_reader    :per_page
  @@per_page = 10

  acts_as_taggable_on :tags
  ActsAsTaggableOn::TagList.delimiter = " "

  belongs_to :owner,
    :class_name => "User",
    :foreign_key => "owner_id"
  has_and_belongs_to_many :members,
    :class_name => "User",
    :foreign_key => "presentation_id",
    :association_foreign_key => "user_id"
  has_many :comments, :dependent => :destroy

  validates_numericality_of :owner_id,
    :only_integer => true,
    :greater_than => 0,
    :message => I18n.t('activerecord.errors.messages.must_have_owner', :resource_name => Presentation.human_name)
  validates_inclusion_of :visible,
    :in => [true, false]
  validates_inclusion_of :editable,
    :in => [true, false]

  validates :access_key, :presence => { :unless => 'visible', :value => true }, :length => { :unless => 'visible', :value => true, :minimum => 4, :maximum => 20 }
  validates :content, :presence => true

  def is_owner?(user)
    return user == owner || new_record?
  end

  def is_visible?(user)
    return true if visible == true || members.exists?(user)
    return is_owner?(user)
  end

  def is_editable?(user)
    return true if editable == true && members.exists?(user)
    return is_owner?(user)
  end

  def is_member?(user)
    return members.exists?(user)
  end

  def self.search(query)
  end

end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_filter :presentation_not_found, :except => [ :index, :new, :create, :index_public, :index_private ]
  before_filter :presentation_visible, :only => [ :show, :run ]
  before_filter :presentation_editable, :only => [ :edit, :update ]
  before_filter :presentation_destroy, :only => [ :destroy ]
  before_filter :only => [:index, :tags] do
    @tags = Presentation.tag_counts
  end

  load_and_authorize_resource

  # note:
  # instancja '@presentation = Presentation.find(params[:id])' dla akcji poza
  # 'index, new, create' znajduje sie w metodzie 'presentation_not_found'

  def index
    #@user = current_user
    #@presentations = @user.presentations
    #if current_user
    query = params[:search]
    @presentations = Presentation.where("(title like ? or description like ?) and visible = ?", "%#{query}%", "%#{query}%", true)
    @tags = Presentation.tag_counts
  end

  def tags
    @fortunes = Presentation.tagged_with(params[:name])
    render 'index'
  end

  def show
    @user = current_user
  end

  def index_private
    @presentations = Presentation.paginate :page => params[:page], :conditions => ['visible = ?', true]
    render 'index_private'
  end

  def index_public
    @presentations = Presentation.paginate :page => params[:page], :conditions => ['visible = ?', true]
    render 'index_public'
  end

  def new
    @user = current_user
    @presentation = Presentation.new
  end

  def create
    @user = current_user
    @presentation = @user.presentations.build(params[:presentation])
    if @presentation.save
      flash[:notice] = t('flash.actions.create.notice', :resource_name => Presentation.human_name)
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def update
    if @presentation.update_attributes(params[:presentation])
      flash[:notice] = t('flash.actions.update.notice', :resource_name => Presentation.human_name)
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  def destroy
    @presentation.destroy
    flash[:notice] = t('flash.actions.destroy.notice', :resource_name => Presentation.human_name)
    redirect_to profile_path
  end

  def edit
    @user = current_user
  end

  def colorize
    
  end

  #TODO
  def subscribe

  end

  def subscribe_create
    if params.has_key?(:access_key) && @presentation.access_key == params[:access_key]
      current_user.member_of << @presentation
      flash[:notice] = t('flash.actions.subscribe.create.notice')
      redirect_to profile_path
    else
      flash[:alert] = t('flash.actions.subscribe.create.alert')
      render 'subscribe'
    end
  end

  def subscribe_destroy
    current_user.member_of.delete(@presentation)
    flash[:notice] = t('flash.actions.subscribe.destroy.notice')
    redirect_to profile_path
  end

  def run
    @content = @presentation.content.gsub("\r","")

    @raw = @content =~ /\A!SLIDE/ ? @content : "!SLIDE\n#{@content}"
    @slides = slides
    @additionals = "shared/slides"
    @presentation_id = params[:id]
    render :layout => 'presentation'
  end

  def watch
    @slide_box = Slide.new('')
    @slides = [ @slide_box ]
    @additionals = "shared/faye_sub"
    @presentation_id = params[:id]
    render :layout => 'presentation'
  end


  private

  def presentation_not_found
    begin
      @presentation = Presentation.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = t('flash.before.not_found', :resource_name => Presentation.human_name)
      redirect_to(presentations_path)
      return false
    end
    return true
  end

  def presentation_visible
    return true if @presentation.is_visible?(current_user)
    flash[:warning] = t('flash.before.subscribe', :resource_name => Presentation.human_name.downcase)
    redirect_to(subscribe_path)
    return false
  end

  def presentation_editable
    if !@presentation.is_owner?(current_user) && params.has_key?(:presentation)
      params[:presentation].delete(:visible) if params[:presentation].has_key?(:visible)
      params[:presentation].delete(:editable) if params[:presentation].has_key?(:editable)
      params[:presentation].delete(:access_key) if params[:presentation].has_key?(:access_key)
    end
    return true if @presentation.is_editable?(current_user)
    flash[:alert] = t('flash.before.access_denied')
    redirect_to(presentations_path)
    return false
  end

  def presentation_destroy
    return true if @presentation.is_owner?(current_user)
    flash[:alert] = t('flash.before.access_denied')
    redirect_to(presentations_path)
    return false
  end

  def slides
    @slides ||= lines.map { |text| Slide.new(text) }
  end

  def lines
    @lines ||= @content.split(/^!SLIDE\s*([a-z\s]*)$/).reject { |line| line.empty? }
    @lines.each { |e| puts "LINIA: " + e }
  end

  class Slide
    attr_accessor :text, :classes, :notes

    def initialize(text, *classes)
      @text    = text
      @classes = classes
      @notes   = nil

      extract_notes!
    end

    def html
      MakersMark::Generator.new(@text).to_html
    end

    private

    def extract_notes!
      @text.gsub!(/^!NOTES\s*(.*\n)$/m) do |note|
        @notes = note.to_s.chomp.gsub('!NOTES', '')
        ''
      end
    end
  end

end

app/helpers/presentations_helper.rb
module PresentationsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/presentations/_form.html.erb
<%= simple_form_for(@presentation) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= f.input :title %>
  <%= f.input :description, :input_html => { :class => "wmd-ignore"} %>
  <%= f.input :tag_list %>
  <% if @presentation.is_owner?(@user) %>
    <fieldset>
      <legend><%= t('form.presentation.fieldset.legend') %></legend>
      <%= f.input :visible, :as => :boolean %>

      <%= f.input :editable, :as => :boolean %>

      <%= f.input :access_key %>
    </fieldset>
  <% end %>
  <%= f.input :content, :as => :text, :input_html => { :id => "inputPane", :class => "input-slides" }  %>
  <%= f.button :submit %>
<% end %>

<%= javascript_include_tag 'showdown.js' %>
<%= javascript_include_tag 'showdown-gui.js' %>
<%= enable_wmd %>

<h2 id="preview-heading">Podląd slajdów</h2>
<div id="slidesBox"></div>

app/views/presentations/_presentation.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Tagi</th>
  </tr>

    <% @presentations.each do |presentation| %>
  <tr>
      <td><%= link_to "#{presentation.title}", presentation %></td>
      <td><%= presentation.description %></td>
      <td><%= presentation.tag_list %></td>
  </tr>
  <% end %>
</table>

app/views/presentations/edit.html.erb
<h2>Edit presentation</h2>
<%= render :partial => 'form' %>

app/views/presentations/index.html.erb
<h2><%= t('presentations.search.head') %></h2>
<h3><%= t('presentations.search.tip') %></h3>

<%= form_tag presentations_path, :method => :get, :remote => true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag t('presentations.search.button'), :name => nil %>
  </p>
<% end %>

  <div id="presentations">
    <%= render 'presentation' %>
  </div>
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, tags_presentation_path(:name=>tag.name), :class => css_class %>
<% end %>

app/views/presentations/index.js.erb
Element.update("presentations", "<%= escape_javascript(render('presentation')) %>");

app/views/presentations/index_private.html.erb
<h2>Tak to jest prywatnie</h2>
<% @presentations.each do |p| -%>
  <div class="presentation-item">
    <p class="title"><%= p.title %></p>
    <p class="desc"><%= p.description %></p>
    <p><%= link_to "Watch!", watch_presentation_path(p) %>
  </div>

<% end -%>
<%= will_paginate @presentations %>

app/views/presentations/index_public.html.erb
<h2>Tak to jest</h2>
<ul>
<% @presentations.each do |p| -%>
  <li><%= p.title %></li>
<% end -%>
</ul>
<%= will_paginate @presentations %>

app/views/presentations/new.html.erb
<h2>Create presentation</h2>

<%= form_for([@user, @presentation], :html => { :multipart => true }) do |f| %>
    <p>
        <%= f.label 'Title' %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label 'Description' %>
        <%= f.text_field :description %>
    </p>
    <p>
        <%= f.label 'File' %>
        <%= f.file_field 'filename' %>
    </p>
    <%= f.submit 'save' %>
<% end %>

app/views/presentations/run.html.erb
<% @slides.each_with_index do |slide, idx| %>
  <div class="">
    <div id="slide-<%= idx %>" class="content">
      <%= slide.html.html_safe %>
    </div>
  </div>
<% end %>

app/views/presentations/show.html.erb
<h2>Show</h2>

<p>Title: <%= @presentation.title %></p>
<p>Description: <%= @presentation.description %></p>

<% if @presentation.is_visible?(@user) %>
  <%= link_to "Run", run_presentation_path(@presentation) %>
<% end %>

<% if @presentation.is_editable?(@user) %>
  <td><%= link_to "Edit", edit_presentation_path(@presentation) %></td>
<% end %>

<% if @presentation.is_member?(@user) %>
  <td><%= link_to "Unsubscribe", subscribe_destroy_path(@presentation), :confirm => "Are you sure?" %></td>
<% else %>
  <td><%= link_to "Subscribe", subscribe_path(@presentation) %></td>
<% end %>

<% if @presentation.comments.any? %>
<p class="comments">
  <%= render @presentation.comments %>
</p>
<% end %>

<p>Add comment</p>
<%= render 'comments/form' %>

app/views/presentations/subscribe.html.erb
<h2>Subscribe</h2>

<p><%= @presentation.title %></p>

<%= form_tag(subscribe_create_path(@presentation), :method => "post") do |f| %>
  <%= label_tag(:access_key, I18n.t('activerecord.attributes.presentation.access_key')) %>
  <%= text_field_tag(:access_key) %>
  <%= submit_tag("Subscribe") %>
<% end %>

app/views/presentations/watch.html.erb
<div class="">
    <div id="slideholder" class="content">
      <h2>Proszę poczekaj...</h2>
    </div>
</div>
  </div>