config/routes.rb
Rails4::Application.routes.draw do
  resources :comments

  scope ':locale' do
    devise_for :users

    resources :presentations do
      resources :comments
      collection do
        get :tags
      end
    end

    match 'presentations/:id/subscribe' => 'presentations#subscribe', :as => 'subscribe'
    match 'presentations/:id/subscribe_create' => 'presentations#subscribe_create', :as => 'subscribe_create'
    match 'presentations/:id/subscribe_destroy' => 'presentations#subscribe_destroy', :as => 'subscribe_destroy'
    match 'presentations/:id/run' => 'presentations#run', :as => 'run_presentation'
    match 'presentations/:id/watch' => 'presentations#watch', :as => 'watch_presentation'
    match 'index_public' => 'presentations#index_public', :as => 'index_public_presentations'
    match 'index_private' => 'presentations#index_private', :as => 'index_private_presentations'

    match 'welcome' => 'welcome#welcome'
    match 'profile' => 'welcome#profile'
    match 'aboutus' => 'welcome#aboutus'
  end
  match 'backend/colorize' => 'backend#colorize'

  match '/(:locale)' => 'welcome#welcome', :as => :root

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails4</title>
    <%= javascript_include_tag :defaults %>
    <%= stylesheet_link_tag "styles", :media => "screen, print" %>
    <%= stylesheet_link_tag "code", :media => "screen, print" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="wrapper">
      <header>
      <h1><a href="#">Monkey Presents: Presentations Hub</a></h1>
      <div id="login-up-corner">
        <% unless user_signed_in? -%>
          <%= link_to t('v.sessions.signin'), new_user_session_path %> <%= t('nav.or') %> 
          <%= link_to t('v.sessions.signup'), new_user_registration_path %>
        <% else -%>
          <%= link_to t('v.sessions.signout'), destroy_user_session_path %>
        <% end -%>

        <div id="languages">
          <%= link_to image_tag("pl.png"), url_for(params.merge({ :locale => "pl" })) %>
          <%= link_to image_tag("gb.png"), url_for(params.merge({ :locale => "en" })) %>
        </div>
      </div>
      </header><hr>

      <section id="main">
      <section id="content">
      <% flash.each do |key, value| -%>
        <div class="flash <%= key %>"><%= value %></div>
      <% end -%>

      <%= yield %>
      </section>

      <aside id="sidebar">
      <nav>
      <ul class="nav">
        <li><%= link_to t('nav.home'), welcome_path %></li>
        <% if user_signed_in? -%>
          <li><%= link_to t("nav.profile"), profile_path %></li>
        <% end -%>
        <li><%= link_to t('nav.show_public'), index_public_presentations_path %></li>
        <li><%= link_to t('nav.watch_private'), index_private_presentations_path %></li>
        <li><%= link_to t('nav.search_public'), presentations_path %></li>
        <li><%= link_to t('nav.about'), aboutus_path %></li>
        <br />
      <% if user_signed_in? %>
          <li><%= link_to t('nav.new_presentation'), new_presentation_path %></li>
          <li><%= link_to t('nav.list_presentation'), profile_path %></li>
      <% end %>
      </ul>

      </nav>
      </aside><!-- end of sidebar -->
      </section><!-- end of #main content and sidebar -->

      <footer>
      <section id="footer-area">

      <section id="footer-outer-block">
      <aside class="footer-segment">
      <h4>Rails</h4>
      <ul>
        <li><a href="http://railstutorial.org">railstutorial.com</a></li>
        <li><a href="http://www.railscasts.com">railscasts.com</a></li>
        <li><a href="http://inf.ug.edu.pl/~wbzyl">WBzyl on rails:)</a></li>
      </ul>
      </aside><!-- end of #second footer segment -->

      <aside class="footer-segment">
      <h4>Meet Downs!</h4>
      <ul>
        <li><a href="daringfireball.net/projects/markdown/">Markdown</a></li>
        <li><a href="http://attacklab.net/showdown/">Showdown</a></li>
        <li><a href="https://github.com/nakajima/slidedown">Slidedown</a></li>
      </ul>
      </aside><!-- end of #third footer segment -->

      <aside class="footer-segment">
      <h4> </h4>
      <p>&copy; 2011 <a href="http://sigma.ug.edu.pl/~awieruck">olkowo</a> Have fun. Page created on base of Bubblecosm template.</p>
      </aside><!-- end of #fourth footer segment -->

      </section><!-- end of footer-outer-block -->

      </section><!-- end of footer-area -->
      </footer>

    </div>
  </body>
</html>

app/views/layouts/presentation.html.erb
<html>
  <head>
    <title>Prezentacja</title>

    <%= stylesheet_link_tag 'slides.css', :media => "screen" %>
    <%= stylesheet_link_tag 'code.css', :media => "screen" %>
    <%= javascript_include_tag 'faye-browser' %>

  </head>
  <body>
    <div id="instructions">
      Use the left/right arrow keys to navigate.
    </div>
    <div id="slides">
      <div id="track">
        <%= yield %>
      </div>
    </div>
    <%= render @additionals %>
  </body>
</html>